### ISSUE TITLE
can't show candidate in native wayland

### ISSUE THREAD

**Issue by shun-sfoo** [tonyfettes/fcitx5.nvim#2]
My wm environment is sway, and I don't use xwayland. I can use the plugin but it can't show candidate. Is lgi problem? It can't show candidate in terminal either.

**Comment by tonyfettes** [comment]
Hello, if you use terminal emulator that support wayland input method, I believe you need to disable wayland input method frontend in your Fcitx5 setting, so that your terminal will not intercept your keystrokes and forward them to Fcitx5 itself.

Sorry for not clarifying things up in README.

**Comment by tonyfettes** [comment]
Also, I recommond using the commit tagged with version v0.0.1-alpha, i.e. commit c7b273e9d0ada4d26be3746b1a46e3ab62be2856. Current HEAD is not-usable yet.

**Comment by shun-sfoo** [comment]
Thanks for replying.I try to disable fcitx5 input method front by unset all the fcitx5 environment params and rm fcitx5 config(Is it rgith to disable ? ). But it still not show candidate in neovim.

**Comment by tonyfettes** [comment]
You need to have fcitx5 input method **running**, but have wayland input method frontend module disabled. You could achieve this by
1. Using graphical configuration tool [fcitx5-configtool](https://github.com/fcitx/fcitx5-configtool), I think the distribution you use might have already packaged it. You can open it by click "Configure" at menu pop up when you right-click the tray icon, or you can directly launch it from command line. With it open, navigate to "Addons" tab and choose "Show Advanced options" and the bottom of the window, and deselect the checkbot of item "Wayland Input method frontend" under "Frontend" group.
2. Modify configuration files at `.config/fcitx5/config` (or `${XDG_CONFIG_HOME}/fcitx5/config`), add
```
[Behavior/DisabledAddons]
0=waylandim
```

Also, there is not need to unset all the fcitx5 environment params.

**Comment by tonyfettes** [comment]
If you use method 1 (configtool), here is how it looks like:

https://user-images.githubusercontent.com/29998228/158917712-d1b18ae7-cdd5-4688-b6df-b65ec8d940c7.mp4

**Comment by shun-sfoo** [comment]
It works!!! Thanks for your tutorial. I disable wayland input method front and use 'v0.0.1-alpha' and it works.Thank you again!
![20220318_10h41m22s_grim](https://user-images.githubusercontent.com/33741766/158927952-b8b47ef5-7b2a-490d-847d-9277f5342bdb.png)
